
                  BellaBeat Company

#Buiness task 
Analyze smart device usage data in order to gain insight into how people are 
already using their smart devices. Then, give recommendations for 
how these trends can inform Bellabeat marketing strategy

## source of dataset 
ThE dataset generated by respondents to a distributed survey via Amazon Mechanical Turk,
public data that explores smart device users’ daily habits
FitBit Fitness Tracker Data (CC0: Public Domain, dataset made available through 
Mobius): This Kaggle data set contains personal fitness tracker from thirty fitbit users. 
Thirty eligible Fitbit users consented to the submission of personal tracker data, 
including minute-level output for physical activity, heart rate, and sleep monitoring. 
It includes information about daily activity, steps, and heart rate that can be used to explore users’ habits. 

## QUESTION ASK 
# 1.What are some trends in smart device usage?
# 2. How could these trends apply to Bella beat customers?
# 3. How could these trends help influence Bella beat marketing strategy? 

library(tidyverse)
library(corrplot)


## Loading data set 
setwd("C:/Users/hp/OneDrive/Desktop/Data/fitbase")

daily<-read.csv("dailyActivity_merged.csv")
sleep<-read.csv("sleepDay_merged.csv")


##  cleaning  and checking Data 

head(daily)
anyNA(daily)
dim(daily)
str(daily)

daily<-daily%>%   # selecting specific columns 
  select("Id" ,"ActivityDate","TotalDistance", "TotalSteps","VeryActiveMinutes",
         "Calories")%>%
  rename(Date=ActivityDate) #renaming 

## for sleep data 

head(sleep)
anyNA(sleep)
dim(sleep)
str(sleep)

sleep<- sleep%>%  #separating date and time 
  separate(SleepDay, sep=" ",into = c ("Date" , "time"))

sleep<-sleep%>%  #selecting specific columns 
  select("Id" , "Date","TotalTimeInBed")


## Merging data set 
Ds<-merge(sleep,daily, by = c("Id","Date"))

com<-Ds%>% ##selecting  specific columns 
  select("VeryActiveMinutes", "Calories","TotalDistance","TotalSteps",
         "TotalTimeInBed")







# Analysis

##Checking trends in data set

## Relationship between total_steps and Calories
ggplot(daily,aes(TotalSteps,Calories))+geom_point(shape=15,color="black")+
  geom_smooth(color="red")+theme_dark()+
  labs(title = "Relationship between Totoal Stpes & Calories")

The total number of steps taken by users and calories burnt have been found to positively correlate.
This implies that the calories burnt rise along with the number of steps taken.


## Relationship between total_distance  and Calories
ggplot(daily,aes( TotalDistance,Calories))+geom_point()+theme_light()+
  labs(title = "Relationship between Total Distance and Calories") + theme(plot.background = 
element_rect(color = "green",fill="grey"),plot.title = element_text(face = "bold",
                                                                          color = "White"))

Total distance traveled and calories burned have a tenuous positive association.
This implies that when a person moves farther, they start to burn calories, but 
not as much, depending on the individual

## Relationship between total_steps and total distance 
ggplot(daily,aes(TotalSteps,TotalDistance))+geom_point(shape=12,color="purple")+
  geom_smooth(color="green")+theme_light()+
  labs(title = "Relationship between Totoal Stpes & Totoal Distance ")

It is true that a person must take more steps in order to get farther on foot.
 

  

## Relationship between total step and total in bed
ggplot(Ds,aes(TotalTimeInBed,TotalSteps))+geom_point(shape=12,color="purple")+
  geom_smooth(color="green")+theme_light()+
  labs(title = "Relationship between Totoal Time In  Bed  & Totoal Distance")

The number of steps or walks taken decreases when a person spends more time in bed,
however not at a particularly rapid rate because other factors might be at play.


##Relationship between total step and total in bed
ggplot(Ds,aes(TotalTimeInBed,Calories))+geom_point(shape=19,color="red")+
  geom_smooth(color="green")+theme_dark()+
  labs(title = "Relationship between Totoal Time In  Bed  & Calories")

The quantity of calories consumed and the overall length of time spent in bed have
a modest negative association. This may not always be the case since other criteria, 
such as the sort of employment and the amount of exercise involved, will also be 
taken into consideration.


## Relationship between very active minutes  and Calories 
ggplot(daily,aes(VeryActiveMinutes,Calories))+geom_point(shape=12,color="purple")+
  geom_smooth(color="green")+theme_light()+
  labs(title = "Relationship Between very Active Minutes  and Calories  ")

Moreover, highly Active Mints and the number of calories in a serving have a weakly
positive association. This may not always be the case since other criteria, 
such as the sort of employment and exercise involved, will also be taken into 
consideration.


## correlation  diagram of com data 
plot(com)
cor(com, method ="spearman")
p<-cor(com, method ="spearman")
corrplot(p, method = "number")



#### Conclusion and Recommendation
1.What are some trends in smart device usage?
  
  # The results from the data shows that there is a positive relationship in High very active minutes of users,
  total distance covered, and total steps to calories burnt. Therefore, a user who
is very active for more minutes will have increase in calories burnt and also any user
covering more distance and taken more steps daily will also have an increase in calories burnt recorded by the device.
Daily habit of spending more time in bed result indicate that a user will have less very active minutes,
and also may not or will burn less calories during the day, and will also have fewer total steps count by the device.
More count on total steps helps in covering more distance.

 2. How could these trends apply to Bellabeat customers?
   
   # Bellabeat can ensure their customers on having more very active minutes or having more
   total steps count by their product will result in burning more calories, and for customers who want 
 to burn more calories can try having more walk and high very active minutes count by their device.
 


 3 how these trends can inform Bellabeat marketing strategy ?
 
 Bellabeat company can set a notification system on their device to inform user on 
 if they have lose or gain more calories use the trends and also predict on their daily
 toatal step, very active minute and total distance using their total time spend in bed.
 This may let more people hsve intrest in their product.